version: '3.8'

services:
  db:
    image: postgres:14-bullseye
    container_name: db
    ports:
      - "37001:5432"
    volumes:
      - ./db:/bitnami/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres